/*
DECLARE @XDTK XML -- DICHIARAZIONE DI UN CONTENITORE (INIZIALMENTE E' VUOTO)
DECLARE @XDTK_EL XML -- DICHIARAZIONE DI UN CONTENITORE (INIZIALMENTE E' VUOTO)

SET	@XDTK = ETL.WriteXDTK(@XDTK, 1, 1000, NULL, '2017-01-01', 22)
SET	@XDTK = ETL.WriteXDTK(@XDTK, 2, 1600, NULL, '2017-01-01', 23)
SET	@XDTK = ETL.WriteXDTK(@XDTK, 3, NULL, 1200, '2018-01-01', 29)

SELECT @XDTK_EL = (SELECT * FROM ETL.GetAllXDTK(@XDTK) FOR XML PATH('DeltaTicketIn_Out'), ROOT('root'), TYPE, ELEMENTS) -- MOSTRA L'ELENCO IN FORMATO XML ELEMENTS

SELECT dbo.XML2JSON(@XDTK_EL) AS JSON_DeltaTicketIN_OUT
*/
ALTER FUNCTION [dbo].[XML2JSON](@inputXML_EL XML)
RETURNS varchar(MAX)
AS
BEGIN
	DECLARE 
			@retVal varchar(MAX) = NULL

	IF @inputXML_EL IS NOT NULL
		BEGIN
			SET @retVal = CAST(dbo.FlattenedJSON(@inputXML_EL) AS varchar(MAX))

			IF @retVal IS NULL -- XML molto complesso
				BEGIN
					DECLARE	@MyHierarchy Hierarchy
					INSERT	@myHierarchy
					SELECT * FROM dbo.ParseXML(@inputXML_EL)

					SET @retVal = CAST(dbo.ToJSON(@MyHierarchy) AS varchar(MAX))
				END

		END
	RETURN @retVal
END