DECLARE 
		@XGAME XML
		,@XVLT XML

EXEC	ETL.ExtractGAME 
		@ConcessionaryID = 7
		,@XGAME = @XGAME OUTPUT

SELECT	*
FROM	ETL.GetAllXGAME(@XGAME)

EXEC	ETL.ExtractVLT 
		@ConcessionaryID = 7
		,@ClubID = 1000252
		,@XVLT = @XVLT OUTPUT

SELECT	*
FROM	ETL.GetAllXVLT(@XVLT) -- MOSTRA L'ELENCO DEI VALORI CONTENUTI

