EXEC	spSelInsUpdDelCpyRULEJOIN_N 'SEL'
EXEC	spSelInsUpdDelCpyRULEJOIN 'UPD',1, NULL, NULL, NULL, 'INNER JOIN'
EXEC	spSelInsUpdDelCpyRULEJOIN_N 'DEL', NULL, NULL, 'dbo.TAB_CONTR_031CM','dbo.TAB_LAV_031CM','LEFT JOIN'

SELECT	*
FROM	RULES_JOINS WITH(NOLOCK)
WHERE	ALIAS LIKE 'JOINTEST%'

SELECT	COUNT(*)
FROM	RULES_JOINS WITH(NOLOCK)
WHERE	ALIAS LIKE (SELECT ALIAS FROM RULES_JOINS WITH(NOLOCK) WHERE IDRuleJOIN = 1) + '%'


