/*
SELECT * FROM VTAB_CONTR_031CM_BASEVAR

-----------------------------------------------------------
-- ESEMPIO DI FILTRO CON TOLLERANZA DEL 10% A SCENDERE
-- OVVERO, ESCLUDENDO O INCLUDENDO I VALORI CHE RIENTRANO
-- NELLA PERCENTUALE STABILITA DI UNA DETERMINATA SOGLIA.
-- DATA UNA SOGLIA CONTR_BASE_CALC_BASE = 80 ED UN VALORE
-- PERCENTUALE PARI A 10, SARA' VERIFICATO SE IL CAMPO
-- DA CONFRONTARE, CONTR_BASE_MOD, SI TROVI NELL'INTERVALLO
-- TRA LA SOGLIA-10% E LA SOGLIA STESSA; SE IL CAMPO VALE 80
-- LA FORMULA APPLICATA SARA' 80-(80*10/100)=72
-- QUINDI IL CAMPO DA CONFRONTARE DOVRA' TROVARSI TRA
-- 72 E 80 AFFINCHE' IL RISULTATO DELLA FUNZIONE SIA 1
-- SE L'ULTIMO PARAMETRO DELLA FUNZIONE dbo.fnIsInRange 
-- (@allowOverRange) VIENE VALORIZZATO AD 1, IL RISULTATO
-- DELLA FUNZIONE SARA' 1 ANCHE QUALORA IL CAMPO DA
-- CONFRONTARE SUPERI LA SOGLIA (QUINDI UN VALORE > 80)
-----------------------------------------------------------
DECLARE	@perc smallint = 10

--------------------------------------------------------------------------------------------------------
-- IN TOLLERANZA
--------------------------------------------------------------------------------------------------------
-- in tolleranza (esclusi i valori che superano la soglia, Azienda 04656750652)
SELECT
		'In tolleranza (esclusi i valori che superano la soglia), Azienda 04656750652' AS Analisi
		,CONTR_BASE_CALC_BASE
		,CONTR_BASE_MOD AS CONTR_BASE_MOD_VAR
		,* 
FROM	VTAB_CONTR_031CM_BASEVAR
WHERE	COD_RETR_BASE = 'RN'
AND		CF_AZIENDA = '04656750652'
AND		dbo.fnIsInRange(CONTR_BASE_MOD, CONTR_BASE_CALC_BASE, @perc, 0) = 1

-- in tolleranza (esclusi i valori che superano la soglia, Azienda MRTDSL63S12C286L)
SELECT
		'In tolleranza (esclusi i valori che superano la soglia), Azienda MRTDSL63S12C286L' AS Analisi
		,CONTR_BASE_CALC_BASE
		,CONTR_BASE_MOD AS CONTR_BASE_MOD_VAR
		,* 
FROM	VTAB_CONTR_031CM_BASEVAR
WHERE	COD_RETR_BASE = 'RN'
AND		CF_AZIENDA = 'MRTDSL63S12C286L'
AND		dbo.fnIsInRange(CONTR_BASE_MOD, CONTR_BASE_CALC_BASE, @perc, 0) = 1


-- in tolleranza (compresi i valori che superano la soglia, Azienda 04656750652)
SELECT
		'In tolleranza (compresi i valori che superano la soglia), Azienda 04656750652' AS Analisi
		,CONTR_BASE_CALC_BASE
		,CONTR_BASE_MOD AS CONTR_BASE_MOD_VAR
		,* 
FROM	VTAB_CONTR_031CM_BASEVAR
WHERE	COD_RETR_BASE = 'RN'
AND		CF_AZIENDA = '04656750652'
AND		dbo.fnIsInRange(CONTR_BASE_MOD, CONTR_BASE_CALC_BASE, @perc, 1) = 1

-- in tolleranza (compresi i valori che superano la soglia, Azienda MRTDSL63S12C286L)
SELECT
		'In tolleranza (compresi i valori che superano la soglia), Azienda MRTDSL63S12C286L' AS Analisi
		,CONTR_BASE_CALC_BASE
		,CONTR_BASE_MOD AS CONTR_BASE_MOD_VAR
		,* 
FROM	VTAB_CONTR_031CM_BASEVAR
WHERE	COD_RETR_BASE = 'RN'
AND		CF_AZIENDA = 'MRTDSL63S12C286L'
AND		dbo.fnIsInRange(CONTR_BASE_MOD, CONTR_BASE_CALC_BASE, @perc, 1) = 1
--------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------
-- FUORI TOLLERANZA
--------------------------------------------------------------------------------------------------------
-- fuori tolleranza (esclusi i valori che superano la soglia, Azienda 04656750652)
SELECT	
		'Fuori tolleranza (esclusi i valori che superano la soglia), Azienda 04656750652' AS Analisi
		,CONTR_BASE_CALC_BASE
		,CONTR_BASE_MOD AS CONTR_BASE_MOD_VAR
		,CAST(CONTR_BASE_CALC_BASE * @perc / 100 AS decimal(13,2)) AS MASSIMA_VARIAZIONE_AMMESSA
		,CONTR_BASE_CALC_BASE - CONTR_BASE_MOD AS VARIAZIONE_RILEVATA
		,((CONTR_BASE_CALC_BASE - CONTR_BASE_MOD) - CAST(CONTR_BASE_CALC_BASE * @perc / 100 AS decimal(13,2))) AS SFORAMENTO
		,* 
FROM	VTAB_CONTR_031CM_BASEVAR
WHERE	COD_RETR_BASE = 'RN'
AND		CF_AZIENDA = '04656750652'
AND		dbo.fnIsInRange(CONTR_BASE_MOD, CONTR_BASE_CALC_BASE, @perc, 0) = 0

-- fuori tolleranza (esclusi i valori che superano la soglia), Azienda MRTDSL63S12C286L
SELECT	
		'Fuori tolleranza (esclusi i valori che superano la soglia), Azienda MRTDSL63S12C286L' AS Analisi
		,CONTR_BASE_CALC_BASE
		,CONTR_BASE_MOD AS CONTR_BASE_MOD_VAR
		,CAST(CONTR_BASE_CALC_BASE * @perc / 100 AS decimal(13,2)) AS MASSIMA_VARIAZIONE_AMMESSA
		,CONTR_BASE_CALC_BASE - CONTR_BASE_MOD AS VARIAZIONE_RILEVATA
		,((CONTR_BASE_CALC_BASE - CONTR_BASE_MOD) - CAST(CONTR_BASE_CALC_BASE * @perc / 100 AS decimal(13,2))) AS SFORAMENTO
		,* 
FROM	VTAB_CONTR_031CM_BASEVAR
WHERE	COD_RETR_BASE = 'RN'
AND		CF_AZIENDA = 'MRTDSL63S12C286L'
AND		dbo.fnIsInRange(CONTR_BASE_MOD, CONTR_BASE_CALC_BASE, @perc, 0) = 0

-- fuori tolleranza (compresi i valori che superano la soglia, Azienda 04656750652)
SELECT	
		'Fuori tolleranza (compresi i valori che superano la soglia), Azienda 04656750652' AS Analisi
		,CONTR_BASE_CALC_BASE
		,CONTR_BASE_MOD AS CONTR_BASE_MOD_VAR
		,CAST(CONTR_BASE_CALC_BASE * @perc / 100 AS decimal(13,2)) AS MASSIMA_VARIAZIONE_AMMESSA
		,CONTR_BASE_CALC_BASE - CONTR_BASE_MOD AS VARIAZIONE_RILEVATA
		,((CONTR_BASE_CALC_BASE - CONTR_BASE_MOD) - CAST(CONTR_BASE_CALC_BASE * @perc / 100 AS decimal(13,2))) AS SFORAMENTO
		,* 
FROM	VTAB_CONTR_031CM_BASEVAR
WHERE	COD_RETR_BASE = 'RN'
AND		CF_AZIENDA = '04656750652'
AND		dbo.fnIsInRange(CONTR_BASE_MOD, CONTR_BASE_CALC_BASE, @perc, 1) = 0

-- fuori tolleranza (compresi i valori che superano la soglia), Azienda MRTDSL63S12C286L
SELECT	
		'Fuori tolleranza (compresi i valori che superano la soglia), Azienda MRTDSL63S12C286L' AS Analisi
		,CONTR_BASE_CALC_BASE
		,CONTR_BASE_MOD AS CONTR_BASE_MOD_VAR
		,CAST(CONTR_BASE_CALC_BASE * @perc / 100 AS decimal(13,2)) AS MASSIMA_VARIAZIONE_AMMESSA
		,CONTR_BASE_CALC_BASE - CONTR_BASE_MOD AS VARIAZIONE_RILEVATA
		,((CONTR_BASE_CALC_BASE - CONTR_BASE_MOD) - CAST(CONTR_BASE_CALC_BASE * @perc / 100 AS decimal(13,2))) AS SFORAMENTO
		,* 
FROM	VTAB_CONTR_031CM_BASEVAR
WHERE	COD_RETR_BASE = 'RN'
AND		CF_AZIENDA = 'MRTDSL63S12C286L'
AND		dbo.fnIsInRange(CONTR_BASE_MOD, CONTR_BASE_CALC_BASE, @perc, 1) = 0
-----------------------------------------------------------
*/
ALTER VIEW	dbo.VTAB_CONTR_031CM_BASEVAR
AS
SELECT 
		B.ID_CONTR AS ID_CONTR_BASE
		,B.DT_MESE_CONTR AS DT_MESE_CONTR_BASE
		,B.ID_DEN031CM AS ID_DEN031CM_BASE
		,B.NUM_MTR_LAV AS NUM_MTR_LAV_BASE
		,B.CF_LAVORATORE AS CF_LAVORATORE_BASE
		,B.TIPO_OPE AS TIPO_OPE_BASE
		,B.COD_AGEV AS COD_AGEV_BASE
		,B.IMP_AGEV AS IMP_AGEV_BASE
		,B.COD_RETR AS COD_RETR_BASE
		,B.MESE_MAX AS MESE_MAX_BASE
		,B.NUM_GIORNI AS NUM_GIORNI_BASE
		,B.IMP_RETR_COMPL AS IMP_RETR_COMPL_BASE
		,B.IMP_CONTR_VERS AS IMP_CONTR_VERS_BASE
		,B.IMP_TRATT_PENS AS IMP_TRATT_PENS_BASE
		,B.DATA_INI_PRDO AS DATA_INI_PRDO_BASE
		,B.IND_EMISS_031R AS IND_EMISS_031R_BASE
		,B.DATA_FINE_PRDO AS DATA_FINE_PRDO_BASE
		,B.IMP_CONTR_CALC AS IMP_CONTR_CALC_BASE
		,B.COD_ALIQ AS COD_ALIQ_BASE
		,B.COD_CAT_LAV AS COD_CAT_LAV_BASE
		,B.TIPO_RAPP_LAV AS TIPO_RAPP_LAV_BASE
		,B.CONTR_BASE_CALC AS CONTR_BASE_CALC_BASE
		,B.CONTR_AGG_CALC AS CONTR_AGG_CALC_BASE
		,B.CONTR_SOLID_CALC AS CONTR_SOLID_CALC_BASE
		,B.CONTR_BASE_MOD AS CONTR_BASE_MOD_BASE
		,B.CONTR_AGG_MOD AS CONTR_AGG_MOD_BASE
		,B.CONTR_SOLID_MOD AS CONTR_SOLID_MOD_BASE
		,B.GG_FASCIA AS GG_FASCIA_BASE
		,B.IMP_RETRIB_PREC AS IMP_RETRIB_PREC_BASE
		,B.COD_BRANO AS COD_BRANO_BASE
		,B.DATA_CRE AS DATA_CRE_BASE
		,B.DATA_AGG AS DATA_AGG_BASE
		,B.UTE_CRE AS UTE_CRE_BASE
		,B.UTE_AGG AS UTE_AGG_BASE

		,V.ID_CONTR
		,V.DT_MESE_CONTR
		,V.ID_LAV031CM
		,V.ID_DEN031CM
		,V.TIPO_OPE
		,V.NUM_MTR_LAV
		,V.COD_AGEV
		,V.IMP_AGEV
		,V.COD_RETR
		,V.MESE_MAX
		,V.NUM_GIORNI
		,V.IMP_RETR_COMPL
		,V.IMP_CONTR_VERS
		,V.IMP_TRATT_PENS
		,V.DATA_INI_PRDO
		,V.IND_EMISS_031R
		,V.DATA_FINE_PRDO
		,V.IMP_CONTR_CALC
		,V.COD_ALIQ
		,V.COD_CAT_LAV
		,V.TIPO_RAPP_LAV
		,V.CONTR_BASE_CALC
		,V.CONTR_AGG_CALC
		,V.CONTR_SOLID_CALC
		,V.CONTR_BASE_MOD
		,V.CONTR_AGG_MOD
		,V.CONTR_SOLID_MOD
		,V.GG_FASCIA
		,V.IMP_RETRIB_PREC
		,V.COD_BRANO
		,V.CF_LAVORATORE
		,V.DATA_CRE
		,V.DATA_AGG
		,V.UTE_CRE
		,V.UTE_AGG

		,D.DATA_INI_COMP
		,D.MATR_AZI
		,D.TIPO_MOD
		,D.DATA_FINE_COMP
		,D.STATO_DENUNCIA
		,D.TOT_GG_LAV
		,D.TOT_RETR
		,D.TOT_CONTR
		,D.TOT_TRATT
		,D.TOT_LAV
		,D.DATA_CHIUSURA
		,D.DATA_CONSOLIDAMENTO
		,D.RIGENERATO
		,D.PROVENIENZA
		,D.ID_TRASMISSIONE
		,D.CF_AZIENDA
		,D.RAGIONESOCIALE
		,D.DENOMINAZIONE
		,D.ID_STATO_VARIAZIONE
		,D.DESC_ERRORE_RICALCOLO
		,D.SEDE_INPS

FROM	dbo.TAB_CONTR_031CM B WITH(NOLOCK) -- BASE
		INNER JOIN
		var.TAB_CONTR_031CM V WITH(NOLOCK) -- VAR
		ON B.DT_MESE_CONTR = V.DT_MESE_CONTR
		AND B.COD_RETR = V.COD_RETR
		AND B.IMP_RETR_COMPL = V.IMP_RETR_COMPL
		AND 
		(
			B.CF_LAVORATORE = V.CF_LAVORATORE
			OR
			B.NUM_MTR_LAV = V.NUM_MTR_LAV
		)
		INNER JOIN
		var.TAB_DEN_031CM D WITH(NOLOCK) -- VAR
		ON V.ID_DEN031CM = D.ID_DEN031CM


